### PR TITLE
Add VSCode devcontainer

### PR DESCRIPTION
**Pull request by mib1185**
This PR will add the VS Code development docker container, which includes
- complete python dev environment
- predefined VSCode tasks for "run setup" and "run tests"
- automated formatting with `Black`
- `pre-commit` hook added to ensure flake8 linting and black formatting before git commit

### CODE REVIEW

**Comment by hthiery** [comment]
could you please add some documentation and I will merge it

**Comment by mib1185** [comment]
yeah sure, where should i add this documentation?

**Comment by hthiery** [comment]
you could add a new directory and simply add a new documentation file for the vscode stuff there

**Comment by mib1185** [comment]
added some documentation

**Pull request merged**
