### PR TITLE
add windows_open_endtime property to thermostat

### PR DESCRIPTION
**Pull request by c-logic**

### CODE REVIEW

**Comment by hthiery** [comment]
Could you please do some cleanup for these changes and add a unittest for it? Please melt your changes into one commit, add a proper commit message and a your signed-off-by tag.

**Comment by hthiery** [comment]
Please rebase your branch and create only one commit for these changes. Then do a force push to update the PR.

**Comment by c-logic** [comment]
Close to rebase and commit new

**Comment by hthiery** [comment]
you could do a rebase on your branch  (meld all the commits to one) and then do a force push to the github repo/branch. with that the need to create a new pull-request would not be needed. nethertheless you have opened a new one, this is also ok.

**Pull request closed without merging**
