### PR TITLE
adds support for blinds like RolloTron 1213

### PR DESCRIPTION
**Pull request by Gezzo42**
I want to use the Rademacher RolloTron 1213 and therefore extended python-fritzhome.

### CODE REVIEW

**Comment by hthiery** [comment]
this looks good .. could you please add some tests before merging it

**Comment by hthiery** [comment]
could you please rebase to master and update your PR?

**Comment by Gezzo42** [comment]
Rebase is done. I will add a test in the next weeks.

**Comment by hthiery** [comment]
any news on the tests?

**Comment by Gezzo42** [comment]
Sorry for the delay, but finally the tests. Is it ok like this?

**Comment by hthiery** [comment]
would you like to add the supported devices in the README?

**Comment by Gezzo42** [comment]
Would be nice. I added the tested device RADEMACHER RolloTron DECT 1213 to the readme. According to https://avm.de/smarthome/mit-fritz-kompatible-geraete/ also the Becker BoxCTRL should be compatible too, but I do not have the device and can not test it.

**Pull request merged**
