### PR TITLE
Refactor/diamond pattern

### PR DESCRIPTION
**Pull request by refinedcranberry**
This PR aims to split the huge FritzhomeDevice class into smaller subclasses - each with their own test.
The overall goal is to improve readability and better testability of each device-type.

still, this PR doesn't address codeclimate yet

### CODE REVIEW

**Comment by hthiery** [comment]
Thanks a lot for the refactoring

**Comment by hthiery** [comment]
just checked your changes and observed that one of the commits breaks the function of the cli.

It is no longer possible to show the list of devices. Could you please check that?

**Comment by refinedcranberry** [comment]
sure, will provide a fix!

**Comment by hthiery** [comment]
Just did a bisect. b32086441459363138134272c1cc72337550dcf2 seems to break the function of getting the list of devices.

**Comment by refinedcranberry** [comment]
totally correct, what is needed is a call to `FritzHome.update_devices()` right after the login so the list of devices gets populated.
to fix manually, just add `fritzbox.update_devices()` right after line 190 in `cli.py`

fix is already implemented and (manually) tested, see https://github.com/hthiery/python-fritzhome/pull/43. i will try to write a proper test for the CLI functionality and provide that as a separate PR.

**Comment by hthiery** [comment]
already did this and can confirm it works. but i'm not sure if this should be the right way. I think login and get_devices is more intuitive for access. So what about doing an update in get_devices in case the list is empty?

**Pull request merged**
